<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quantization-tables [
<!ELEMENT quantization-tables (table)+>
<!ELEMENT table (description , levels)>
<!ELEMENT description (CDATA)>
<!ELEMENT levels (CDATA)>
<!ATTLIST table slot ID #REQUIRED>
<!ATTLIST levels width CDATA #REQUIRED>
<!ATTLIST levels height CDATA #REQUIRED>
<!ATTLIST levels divisor CDATA #REQUIRED>
]>
<!--
  JPEG quantization tables.
-->
<quantization-tables>
  <table slot="0" alias="luminance">
    <description>Luminance Quantization Table</description>
    <levels width="8" height="8" divisor="1">
		16, 12, 13, 16, 22,  33,  51,  69,
		12, 13, 14, 19, 25,  47,  63,  76,
		13, 14, 17, 24, 39,  57,  76,  83,
		16, 19, 24, 30, 54,  78,  91,  96,
		22, 25, 39, 54, 70,  104, 123, 129,
		33, 47, 57, 78, 104, 124, 159, 154,
		51, 63, 76, 91, 123, 159, 193, 201,
		69, 76, 83, 96, 129, 154, 201, 248
    </levels>
  </table>

  <table slot="1" alias="chrominance">
    <description>Chrominance Quantization Table</description>
    <levels width="8" height="8" divisor="1">
		17,  18,  24,  47,   99,   128,  192,  256,
		18,  21,  26,  66,   99,   192,  256,  512,
		24,  26,  56,  99,   128,  256,  512,  512,
		47,  66,  99,  128,  256,  512,  1024, 1024,
		99,  99,  128, 256,  512,  1024, 2048, 2048,
		128, 192, 256, 512,  1024, 2048, 4096, 4096,
		192, 256, 512, 1024, 2048, 4096, 8192, 8192,
		256, 512, 512, 1024, 2048, 4096, 8192, 8192
    </levels>
  </table>
</quantization-tables>
