<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quantization-tables [
<!ELEMENT quantization-tables (table)+>
<!ELEMENT table (description , levels)>
<!ELEMENT description (CDATA)>
<!ELEMENT levels (CDATA)>
<!ATTLIST table slot ID #REQUIRED>
<!ATTLIST levels width CDATA #REQUIRED>
<!ATTLIST levels height CDATA #REQUIRED>
<!ATTLIST levels divisor CDATA #REQUIRED>
]>
<!--
  JPEG quantization tables.
-->
<quantization-tables>
  <table slot="0" alias="luminance">
    <description>Luminance Quantization Table</description>
    <levels width="8" height="8" divisor="1">
		16, 11, 12, 15, 21,  32,  50,  66,
		11, 12, 13, 18, 24,  46,  62,  73,
		12, 13, 16, 23, 38,  56,  73,  75,
		15, 18, 23, 29, 53,  75,  83,  80,
		21, 24, 38, 53, 68,  95,  103, 94,
		32, 46, 56, 75, 95,  104, 117, 96,
		50, 62, 73, 83, 103, 117, 120, 102,
		66, 73, 75, 80, 94,  96,  102, 87
    </levels>
  </table>

  <table slot="1" alias="chrominance">
    <description>Chrominance Quantization Table</description>
    <levels width="8" height="8" divisor="1">
		17,  18,  24,  47,  99,   99,   128,  192,
		18,  21,  26,  66,  99,   99,   128,  192,
		24,  26,  56,  99,  99,   128,  192,  256,
		47,  66,  99,  99,  128,  192,  256,  512,
		99,  99,  99,  128, 192,  256,  512,  1024,
		99,  99,  128, 192, 256,  512,  1024, 2048,
		128, 128, 192, 256, 512,  1024, 2048, 4096,
		192, 192, 256, 512, 1024, 2048, 4096, 8192
    </levels>
  </table>
</quantization-tables>
