<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quantization-tables [
<!ELEMENT quantization-tables (table)+>
<!ELEMENT table (description , levels)>
<!ELEMENT description (CDATA)>
<!ELEMENT levels (CDATA)>
<!ATTLIST table slot ID #REQUIRED>
<!ATTLIST levels width CDATA #REQUIRED>
<!ATTLIST levels height CDATA #REQUIRED>
<!ATTLIST levels divisor CDATA #REQUIRED>
]>
<!--
  JPEG quantization tables.
-->
<quantization-tables>
  <table slot="0" alias="luminance">
    <description>Luminance Quantization Table</description>
    <levels width="8" height="8" divisor="1">
		16, 11, 13, 16,  20,  29,  44,  73,
		11, 12, 13, 16,  21,  30,  46,  76,
		13, 13, 15, 18,  24,  34,  52,  85,
		16, 16, 18, 22,  29,  41,  63,  103,
		20, 21, 24, 29,  38,  54,  82,  135,
		29, 30, 34, 41,  54,  76,  116, 192,
		44, 46, 52, 63,  82,  116, 177, 293,
		73, 76, 85, 103, 135, 192, 293, 484
    </levels>
  </table>

  <table slot="1" alias="chrominance">
    <description>Chrominance Quantization Table</description>
    <levels width="8" height="8" divisor="1">
		17,   18,   27,    51,    124,   395,   1617,  8563,
		18,   21,   30,    58,    141,   449,   1838,  9734,
		27,   30,   45,    85,    208,   659,   2701,  12725,
		51,   58,   85,    161,   395,   1251,  5127,  12725,
		124,  141,  208,   395,   968,   3070,  12580, 12725,
		395,  449,  659,   1251,  3070,  9734,  12725, 12725,
		1617, 1838, 2701,  5127,  12580, 12725, 12725, 12725,
		8563, 9734, 12725, 12725, 12725, 12725, 12725, 12725
    </levels>
  </table>

  <table slot="2" alias="chrominance2">
    <description>Chrominance Quantization Table 2</description>
    <levels width="8" height="8" divisor="1">
		17,   18,   25,   43,   92,   245,    813,   3358,
		18,   20,   28,   48,   102,   273,   907,   3745,
		25,   28,   38,   66,   142,   379,   1258,  5195,
		43,   48,   66,   114,  245,   654,   2170,  8965,
		92,   102,  142,  245,  525,   1403,  4658,  12725,
		245,  273,  379,  654,  1403,  3745,  12436, 12725,
		813,  907,  1258, 2170, 4658,  12436, 12725, 12725,
		3358, 3745, 5195, 8965, 12725, 12725, 12725, 12725
    </levels>
  </table>
</quantization-tables>
