<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE quantization-tables [
<!ELEMENT quantization-tables (table)+>
<!ELEMENT table (description , levels)>
<!ELEMENT description (CDATA)>
<!ELEMENT levels (CDATA)>
<!ATTLIST table slot ID #REQUIRED>
<!ATTLIST levels width CDATA #REQUIRED>
<!ATTLIST levels height CDATA #REQUIRED>
<!ATTLIST levels divisor CDATA #REQUIRED>
]>
<!--
  JPEG quantization tables.
-->
<quantization-tables>
  <table slot="0" alias="luminance">
    <description>Luminance Quantization Table</description>
    <levels width="8" height="8" divisor="1">
		11, 11, 12,  15,  20,  27,   36,   47,
		11, 12, 15,  20,  27,  36,   47,   93,
		12, 15, 20,  27,  36,  47,   93,   185,
		15, 20, 27,  36,  47,  93,   185,  369,
		20, 27, 36,  47,  93,  185,  369,  737,
		27, 36, 47,  93,  185, 369,  737,  1473,
		36, 47, 93,  185, 369, 737,  1473, 2945,
		47, 93, 185, 369, 737, 1473, 2945, 5889
    </levels>
  </table>

  <table slot="1" alias="chrominance">
    <description>Chrominance Quantization Table</description>
    <levels width="8" height="8" divisor="1">
		12,  15,  18,   26,   39,   69,   139,   279,
		15,  18,  26,   39,   69,   139,  279,   559,
		18,  26,  39,   69,   139,  279,  559,   1119,
		26,  39,  69,   139,  279,  559,  1119,  2239,
		39,  69,  139,  279,  559,  1119, 2239,  4479,
		69,  139, 279,  559,  1119, 2239, 4479,  8959,
		139, 279, 559,  1119, 2239, 4479, 8959,  17919,
		279, 559, 1119, 2239, 4479, 8959, 17919, 35839
    </levels>
  </table>
</quantization-tables>
